services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    network_mode: host  # Required for network scanning
    cap_add:
      - NET_ADMIN
      - NET_RAW
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
        - action: rebuild
          path: requirements.txt # Rebuild if dependencies change

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - node_modules:/frontend/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:3000
    depends_on:
      - backend
    restart: unless-stopped
    

volumes:
  backend:
  sqlite_data:
  node_modules:
  