services:
  backend:
    build:
      context: ./backend
    command: python app.py
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
        - action: rebuild
          path: requirements.txt # Rebuild if dependencies change
    stop_signal: SIGINT
    ports: 
      - 5000:5000

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:3000
    depends_on:
      - backend
    restart: unless-stopped

  