services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ./backend:/backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
    - "3000:3000"
    # volumes:
    #   - ./frontend:/frontend
    #   - /frontend/node_modules
    develop:
      watch:
        - action: sync
          path: ./frontend/src
          target: /frontend/dist
          initial_sync: true
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json