/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WifiRouteImport } from './routes/Wifi'
import { Route as TracerouteRouteImport } from './routes/Traceroute'
import { Route as DevicesRouteImport } from './routes/Devices'
import { Route as DNSRouteImport } from './routes/DNS'
import { Route as IndexRouteImport } from './routes/index'

const WifiRoute = WifiRouteImport.update({
  id: '/Wifi',
  path: '/Wifi',
  getParentRoute: () => rootRouteImport,
} as any)
const TracerouteRoute = TracerouteRouteImport.update({
  id: '/Traceroute',
  path: '/Traceroute',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesRoute = DevicesRouteImport.update({
  id: '/Devices',
  path: '/Devices',
  getParentRoute: () => rootRouteImport,
} as any)
const DNSRoute = DNSRouteImport.update({
  id: '/DNS',
  path: '/DNS',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/DNS': typeof DNSRoute
  '/Devices': typeof DevicesRoute
  '/Traceroute': typeof TracerouteRoute
  '/Wifi': typeof WifiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/DNS': typeof DNSRoute
  '/Devices': typeof DevicesRoute
  '/Traceroute': typeof TracerouteRoute
  '/Wifi': typeof WifiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/DNS': typeof DNSRoute
  '/Devices': typeof DevicesRoute
  '/Traceroute': typeof TracerouteRoute
  '/Wifi': typeof WifiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/DNS' | '/Devices' | '/Traceroute' | '/Wifi'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/DNS' | '/Devices' | '/Traceroute' | '/Wifi'
  id: '__root__' | '/' | '/DNS' | '/Devices' | '/Traceroute' | '/Wifi'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DNSRoute: typeof DNSRoute
  DevicesRoute: typeof DevicesRoute
  TracerouteRoute: typeof TracerouteRoute
  WifiRoute: typeof WifiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/Wifi': {
      id: '/Wifi'
      path: '/Wifi'
      fullPath: '/Wifi'
      preLoaderRoute: typeof WifiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Traceroute': {
      id: '/Traceroute'
      path: '/Traceroute'
      fullPath: '/Traceroute'
      preLoaderRoute: typeof TracerouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Devices': {
      id: '/Devices'
      path: '/Devices'
      fullPath: '/Devices'
      preLoaderRoute: typeof DevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/DNS': {
      id: '/DNS'
      path: '/DNS'
      fullPath: '/DNS'
      preLoaderRoute: typeof DNSRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DNSRoute: DNSRoute,
  DevicesRoute: DevicesRoute,
  TracerouteRoute: TracerouteRoute,
  WifiRoute: WifiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
